### PR TITLE
Allow Symfony3

### PR DESCRIPTION
**Pull request by garak**
(and switch to PSR-4)

### CODE REVIEW

**Comment by yohang** [comment]
I need to test this one.

If switching to PSR-4, we have to remove the `target-dir` of composer.json.

**Comment by garak** [comment]
You're rigth, I also removed `target-dir`

**Comment by garak** [comment]
bump

**Comment by garak** [comment]
bump bump

**Comment by Alabate** [comment]
Bump³

If someone really need it, you can tell Composer to download on Garak fork instead by adding this to your `composer.json`.

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/garak/FrequenceWebCalendRBundle"
        }
    ],

```
and replace your required version with
```
"frequence-web/calendr-bundle": "dev-patch-2",
```

**Comment by garak** [comment]
I also tried to contact @yohang directly via email, but I got no reply.
Too bad :disappointed:

**Comment by OnekO** [comment]
Bump.

If there is no response from @yohang, @garak should upload his patch to packagist.

**Comment by mpdude** [comment]
Bump<sup>5</sup>!

Also, fixing deprecation notices for Symfony 2.8 would be nice.

Maybe it's time for an official fork?

**Comment by garak** [comment]
@yohang I see that you made changes yourself, so I'll close this.
Not really fair, but at least bundle is not so abandoned

**Pull request closed without merging**
